### ISSUE TITLE
doesn't seem to work with latest 3.0.5 flutter

### ISSUE THREAD

**Issue by evanrich** [irajeshh/FlutterShip#1]
This doesnt't seem to work with the latest flutter/dart.  While Visual  Studio code shows no errors, the code doesn't run.  When I run `flutter pub upgrade`, suddenly TONS of errors show up.   I was trying to replicate your drawer code to learn flutter, but am having a hell of a time getting this to work:
![image](https://user-images.githubusercontent.com/518320/183824858-c3de51fa-c055-491f-90f6-feaef8aae3b1.png)

https://stackoverflow.com/questions/70363918/error-member-not-found-packageroot-how-to-solve-ignore-deprecated-member-u

**Comment by irajeshh** [comment]
This repository is not going to be updated! Pardon.

**Comment by irajeshh** [comment]
@evanrich Now the project is upgraded with null-safety. But 1% of the code may break due to plugin updates.
Now you can fork the master branch, and give it a try.
